"""CSS generation utilities for the MkDocs scouting-report site.

Reads a :class:`~team_colors.TeamPalette` and writes a fully-rendered
``extra.css`` file, replacing every hardcoded colour with the team's
palette.  Derived shades (lighter/darker variants, hover states, transparent
overlays) are computed programmatically so callers only need to maintain the
six canonical palette colours.

Typical usage::

    from utils_css import write_team_css
    write_team_css("ULK", "docs/stylesheets/extra.css")
"""

from team_colors import TEAM_COLORS, TeamPalette

# ── colour arithmetic helpers ──────────────────────────────────────────────────


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Parse a ``#RRGGBB`` string to an (R, G, B) integer tuple.

    Args:
        hex_color: Hex colour string, with or without leading ``#``.

    Returns:
        Tuple of red, green, blue integers in the range [0, 255].
    """
    h = hex_color.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _rgb_to_hex(r: int, g: int, b: int) -> str:
    """Format (R, G, B) integers as a ``#RRGGBB`` hex string.

    Args:
        r: Red channel [0, 255].
        g: Green channel [0, 255].
        b: Blue channel [0, 255].

    Returns:
        Uppercase hex colour string prefixed with ``#``.
    """
    return f"#{r:02X}{g:02X}{b:02X}"


def _lighten(hex_color: str, amount: float) -> str:
    """Blend a colour toward white.

    Args:
        hex_color: Source ``#RRGGBB`` colour.
        amount: Fraction in [0, 1] to blend toward white (0 = unchanged,
            1 = pure white).

    Returns:
        Lightened ``#RRGGBB`` colour string.
    """
    r, g, b = _hex_to_rgb(hex_color)
    r = min(255, int(r + (255 - r) * amount))
    g = min(255, int(g + (255 - g) * amount))
    b = min(255, int(b + (255 - b) * amount))
    return _rgb_to_hex(r, g, b)


def _darken(hex_color: str, amount: float) -> str:
    """Blend a colour toward black.

    Args:
        hex_color: Source ``#RRGGBB`` colour.
        amount: Fraction in [0, 1] to blend toward black (0 = unchanged,
            1 = pure black).

    Returns:
        Darkened ``#RRGGBB`` colour string.
    """
    r, g, b = _hex_to_rgb(hex_color)
    r = max(0, int(r * (1 - amount)))
    g = max(0, int(g * (1 - amount)))
    b = max(0, int(b * (1 - amount)))
    return _rgb_to_hex(r, g, b)


def _rgba(hex_color: str, alpha: float) -> str:
    """Format a colour as a CSS ``rgba(…)`` string.

    Args:
        hex_color: Source ``#RRGGBB`` colour.
        alpha: Opacity in [0, 1].

    Returns:
        CSS ``rgba(R, G, B, alpha)`` string.
    """
    r, g, b = _hex_to_rgb(hex_color)
    return f"rgba({r}, {g}, {b}, {alpha})"


# ── CSS template ───────────────────────────────────────────────────────────────

_CSS_TEMPLATE = """\
/* ============================================================
   EuroLeague Scouting Report — {team_name}
   Generated by utils_css.write_team_css(); do not edit by hand.
   ============================================================ */

/* ---- Palette variables ------------------------------------ */
:root {{
  --team-primary:      {primary};
  --team-bg-darkest:   {bg_darkest};
  --team-bg-header:    {bg_header};
  --team-bg-mid:       {bg_mid};
  --team-bg-light:     {bg_light};
  --team-text-accent:  {text_on_primary};
  --team-green:        #2ECC71;
  --team-red:          #E74C3C;
  --team-white:        #FFFFFF;
  --team-gray:         #CCCCCC;
}}

/* ---- Material slate scheme overrides ---------------------- */
[data-md-color-scheme="slate"] {{
  --md-primary-fg-color:              {primary};
  --md-primary-fg-color--light:       {primary_light};
  --md-primary-fg-color--dark:        {primary_dark};
  --md-accent-fg-color:               {primary};
  --md-accent-fg-color--transparent:  {primary_alpha10};
  --md-default-bg-color:              {bg_darkest};
  --md-default-bg-color--light:       {bg_header};
  --md-default-bg-color--lighter:     {bg_mid};
  --md-default-bg-color--lightest:    {bg_deepest};
  --md-code-bg-color:                 {bg_light};
  --md-typeset-color:                 #FFFFFF;
  --md-typeset-a-color:               {primary};
}}

/* ---- Header ----------------------------------------------- */
.md-header {{
  background-color: {bg_header};
  border-bottom: 3px solid {primary};
}}

.md-header__title {{
  color: {primary};
  font-weight: 700;
  letter-spacing: 0.05em;
}}

/* ---- Navigation ------------------------------------------- */
.md-nav__title {{
  color: {primary};
  background-color: {bg_header};
}}

.md-nav__item .md-nav__link--active {{
  color: {primary};
}}

/* ---- Typography ------------------------------------------- */
.md-typeset h1 {{
  color: {primary};
  border-bottom: 2px solid {primary};
  padding-bottom: 0.3em;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}}

.md-typeset h2 {{
  color: #FFFFFF;
  border-left: 4px solid {primary};
  background-color: {bg_mid};
  padding: 0.45em 0.75em;
  border-radius: 0 4px 4px 0;
  margin-top: 1.5em;
}}

.md-typeset h3 {{
  color: {primary};
  text-transform: uppercase;
  font-size: 0.85em;
  letter-spacing: 0.06em;
}}

/* ---- Tables ----------------------------------------------- */
.md-typeset table:not([class]) {{
  border-collapse: collapse;
  width: 100%;
  font-size: 0.85em;
}}

.md-typeset table:not([class]) th {{
  background-color: {bg_header};
  color: {primary};
  font-weight: 700;
  text-transform: uppercase;
  font-size: 0.78em;
  letter-spacing: 0.05em;
  padding: 0.7em 1em;
  border: 1px solid {bg_mid};
}}

.md-typeset table:not([class]) td {{
  padding: 0.55em 1em;
  border: 1px solid {bg_mid};
  color: #FFFFFF;
}}

.md-typeset table:not([class]) tr:nth-child(even) td {{
  background-color: {bg_mid};
}}

.md-typeset table:not([class]) tr:nth-child(odd) td {{
  background-color: {bg_light};
}}

.md-typeset table:not([class]) tr:hover td {{
  background-color: {bg_hover};
}}

/* ---- Admonitions ------------------------------------------ */
.md-typeset .admonition.tip,
.md-typeset details.tip {{
  border-color: {primary};
}}

.md-typeset .tip > .admonition-title,
.md-typeset .tip > summary {{
  background-color: {primary_alpha10};
}}

.md-typeset .tip > .admonition-title::before,
.md-typeset .tip > summary::before {{
  color: {primary};
}}

.md-typeset .admonition.danger,
.md-typeset details.danger {{
  border-color: #E74C3C;
}}

.md-typeset .admonition.success,
.md-typeset details.success {{
  border-color: #2ECC71;
}}

.md-typeset .admonition.info,
.md-typeset details.info {{
  border-color: {primary};
}}

/* ---- Section letter badge --------------------------------- */
.section-badge {{
  display: inline-block;
  background-color: {primary};
  color: {text_on_primary};
  font-weight: 900;
  font-size: 0.85em;
  padding: 0.1em 0.5em;
  border-radius: 3px;
  margin-right: 0.4em;
}}

/* ---- Cover page (mkdocs-with-pdf) ------------------------- */
#pdf-cover-page {{
  background-color: {bg_darkest} !important;
  color: #FFFFFF !important;
}}

/* ---- Print / PDF export ----------------------------------- */
@media print {{
  body,
  .md-main__inner,
  .md-content {{
    background-color: {bg_darkest} !important;
    color: #FFFFFF !important;
  }}

  h1 {{
    color: {primary} !important;
    border-bottom: 2px solid {primary} !important;
    text-transform: uppercase !important;
    letter-spacing: 0.08em !important;
    page-break-before: always;
  }}

  h1:first-of-type {{
    page-break-before: avoid;
  }}

  h2 {{
    color: #FFFFFF !important;
    border-left: 4px solid {primary} !important;
    background-color: {bg_mid} !important;
    padding: 0.4em 0.75em !important;
  }}

  h3 {{
    color: {primary} !important;
    text-transform: uppercase !important;
  }}

  table th {{
    background-color: {bg_header} !important;
    color: {primary} !important;
    border: 1px solid {bg_mid} !important;
  }}

  table tr:nth-child(even) td {{
    background-color: {bg_mid} !important;
  }}

  table tr:nth-child(odd) td {{
    background-color: {bg_light} !important;
  }}

  table td {{
    color: #FFFFFF !important;
    border: 1px solid {bg_mid} !important;
  }}

  a {{
    color: {primary} !important;
    text-decoration: none !important;
  }}

  .admonition {{
    border-left-width: 4px !important;
    background-color: {bg_mid} !important;
    color: #FFFFFF !important;
  }}
}}
"""


# ── public interface ───────────────────────────────────────────────────────────


def render_team_css(team_code: str) -> str:
    """Render the complete ``extra.css`` content for a given team.

    All derived shades are computed automatically from the six canonical
    palette colours stored in :data:`~team_colors.TEAM_COLORS`.

    Args:
        team_code: Three-letter EuroLeague team code (e.g. ``"ULK"``).

    Returns:
        Fully-rendered CSS string ready to be written to disk.

    Raises:
        KeyError: If *team_code* is not found in ``TEAM_COLORS``.
    """
    palette: TeamPalette = TEAM_COLORS[team_code]

    return _CSS_TEMPLATE.format(
        team_name=palette.name or team_code,
        # canonical colours
        primary=palette.primary,
        bg_darkest=palette.bg_darkest,
        bg_header=palette.bg_header,
        bg_mid=palette.bg_mid,
        bg_light=palette.bg_light,
        text_on_primary=palette.text_on_primary,
        # derived shades
        primary_light=_lighten(palette.primary, 0.20),
        primary_dark=_darken(palette.primary, 0.20),
        primary_alpha10=_rgba(palette.primary, 0.10),
        bg_deepest=_darken(palette.bg_darkest, 0.20),
        bg_hover=_lighten(palette.bg_mid, 0.15),
    )


def write_team_css(team_code: str, output_path: str) -> None:
    """Generate and write the ``extra.css`` file for a given team.

    Args:
        team_code: Three-letter EuroLeague team code (e.g. ``"ULK"``).
        output_path: File path to write the CSS to (e.g.
            ``"docs/stylesheets/extra.css"``).

    Raises:
        KeyError: If *team_code* is not found in ``TEAM_COLORS``.
    """
    css = render_team_css(team_code)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(css)
